spring:
  datasource:
    url: 'jdbc:mysql://116.63.13.220:3306/2021213099'#?createDatabaseIfNotExist=true
    username: 2021213099
    password: 2021213099
#  sql:
#    init:
#      mode: always


logging:
  level:
    sql: debug
    com:
      lxh: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'